[유휘찬][Signup Page]Add : 회원가입 페이지 레이아웃 구현
wecode-bootcamp-korea/11-Teslrider-frontend pull request #4
Opened 2020-08-23 19:35 UTC by chan-97

- 회원가입 페이지 레이아웃 구현
- fetch 함수로 로그인 페이지 로그인 기능구현 준비
- fetch 함수로 회원가입 페이지 회원가입 기능구현 준비
- 로그인, 회원가입 페이지 비밀번호란 "표시" 클릭시 비밀번호 확인 가능
  기능 구현
- 로그인, 회원가입 페이지 사용자가 입력한 정보 state 에 저장

2020-08-25 08:35 UTC, dipsiiiiiiiiii reviewed
고생하셨습니다!
피드백 반영해주시면 바로 머지 할 수 있을 것 같애요!

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/CheckAgreeContainer.js
> +}
깔끔하네요!
비구조화만 습관화되면 더 깔끔할 것 같습니다 👍 
```suggestion
  render() {
  const { check } = this.props;
    return (
      <div className="CheckAgreeContainer">
        <div className="checkboxContainer">
          <input type="checkbox" />
        </div>
        <div className="agreeContainer">
          <div className="userAgree">{check}</div>
        </div>
      </div>
    );
  }
}
```

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/Login.scss
> +  .LoginScreen {
왜 갑자기 다 PascalCase로 바꾸셨죠??
camelCase 사용해주세요 :)

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/LoginScreen.js
> +    });
```suggestion
    const {name, value} = e.target;
    this.setState({
      [name]: value,
    });
```
이렇게도 줄여볼 수 있겠네요 :)

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/LoginScreen.js
> +    console.log(this.state);
테스트 끝난 콘솔은 지워주세요 :)

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +};
단순 string이어서 굳이 객체에 저장해서 관리할 필요가 없을 것 같습니다!
깔끔하게 쓰려고 하시는 이유였으면 그 사고 과정이 너무 좋은 것 같습니다!

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/SignUp/SignupFooter.js
> +      <footer className="SignupFooter">
footer 태그 사용 굿!

2020-08-25 08:35 UTC, dipsiiiiiiiiii commented on src/Pages/LogIn/SignUp/SignupNav.js
> +      <div className="SignupNav">
굳이 div로 한 번 더 감쌀 필요가 없을 것 같습니다!

2020-08-26 04:07 UTC, chan-97 commented on src/Pages/LogIn/CheckAgreeContainer.js
> +}
수정 완료했습니다.
비구조화 할당을 할것을 생각하면서 state 의 키값을 네이밍하면 보다 직관적이고 가독성이 좋은 키 이름을 지을수 있을것 같다는 생각이 드네요😋
더 익숙해질 필요가 있는것 같습니다 감사합니다

2020-08-26 04:08 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +    console.log(this.state);
수정완료했습니다~

2020-08-26 04:32 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +};
깔끔하게 쓰려고 했던 것은 맞습니다! ㅎ
근데 사실 저 string 안에 <a></a> 태그를 넣어야 해서 이런저런 방법을 시도해 보다가 결국 넘어간 거였습니다..

그러니까
```
const check = {
  privacyNotice: `Tesla 계정을 생성함으로써 Tesla의 <a href="/">개인 정보 보호 공지 사항</a> 및 <a href="/>이용 약관</a>을 이해하였으며 이에 동의합니다.`,
  receiveUpdates: `Tesla의 <a href="/">업데이트</a>를 수신하겠습니다.`,
};
```
이런식으로 회원가입 페이지 하단에 이용약관 내용에 대해 동의를 구하는 체크박스가 있는데, 
해당 링크를 클릭하면 개인정보 보호 공지사항 등의 세부 내용을 확인할수 있는 페이지로 이동할 수 있게 되어있더라구요
이부분을 똑같이 구현하려고 객체의 value 에 태그를 넣어봤었는데 잘 되지 않았습니다.
이미 넘어간 부분이긴 하지만 이부분에 대해서 조언해 주시면 더욱 공부가 될 것 같습니다

2020-08-26 04:44 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignupNav.js
> +      <div className="SignupNav">
정신없이 깨지는 css 수정하다 보니 이런 일이 발생했던 것 같습니다 ㅋㅋㅋ

2020-08-26 04:52 UTC, chan-97 commented on src/Pages/LogIn/Login.scss
> +  .LoginScreen {
LoginScreen 이 하나의 컴포넌트 입니다.
Login 컴포넌트 안에 있긴 하지만 LoginScreen 역시 하나의 컴포넌트라 최상위 태그 className 을 upperCase 로 생성해야 한다고 알고 있어서 이렇게 했습니다!
관희님 말씀대로면 컴포넌트 안에있는 컴포넌트의 최상위 태그의 className은 camelCase 로 작성해도 된다는 건가요??

2020-08-26 04:56 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +    });
호오... 비구조화 할당은 렌더 밖에서도 할 수 있다는 것은 알고 있엇지만 실제로 활용해 본 적이 없었습니다
함수 내에서 실제로 비구조화 할당을 하는 것을 보니 무척 새롭네요!!
또다른 비구조화 할당 꿀팁 있으시면 알려주세요!!! ㅎㅎㅎ

2020-08-26 04:56 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignupFooter.js
> +      <footer className="SignupFooter">
허허..ㅎㅎㅎㅎ감사합니다😁😁😁

2020-08-26 18:42 UTC, saengmotmi reviewed
코멘트 확인해주세요!

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/LoginScreen.js
> +  };
👍

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/LoginScreen.js
> +    fetch("http://10.58.1.69:8000/user/signin", {
```suggestion
    fetch(`${API}/user/signin`, {
```
주소 등은 src 폴더 아래 config.js 파일 만들고 그곳에 모아서 관리해주세요

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/LoginScreen.js
> +      visible: this.state.visible === "표시" ? "숨김" : "표시",
보이냐 안보이냐의 문제라면 "표시"라는 문자열 말고 true/false 값으로 관리하는게 더 맞아보이네요

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUp.js
> +      </div>
구웃 👍

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +        isChecked: this.state.isChecked === false ? true : false,
```suggestion
        isChecked: !this.state.isChecked
```

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +      }
테스트 끝났으면 지워주세요

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +    fetch("http://10.58.1.69:8000/user/signup", {
여기 주소도 분리해서 관리해주세요

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +        console.log(res);
테스트 끝났으면 지워주세요

2020-08-26 18:42 UTC, saengmotmi commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +          alert("이메일 주소에 '@'를 포함해 주세요.");
```suggestion
        if (!this.state.last_name)  alert("성에는 글자만 포함될 수 있습니다.");
        if (!this.state.first_name) alert("이름에는 글자만 포함될 수 있습니다.");
        if (!this.state.email) alert("유효한 이메일 주소를 입력해야 합니다.");
        if (!this.state.password) alert("비밀번호가 필요합니다.");
        if (!this.state.isChecked) alert("계속하려면 개인 정보 공지 및 이용 약관에 동의해야 합니다.");
        if (!this.state.email.includes("@")) { alert("이메일 주소에 '@'를 포함해 주세요.");
```
- 개인적으로 else if 문은 가독성이 떨어져서 선호하는 편은 아닙니다
- 뒤에 나오는 문장이 한줄일 경우 한줄로 쓰는게 더 좋다고 생각합니다

2020-08-27 04:50 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUp.js
> +      </div>
행복합니다😋

2020-08-27 04:52 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +      }
수정완료하였습니답!

2020-08-27 07:26 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +        console.log(res);
수정완료했습니다~

2020-08-27 07:29 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +          alert("이메일 주소에 '@'를 포함해 주세요.");
훨씬 가독성이 좋아졌네요!! 
감사합니답

2020-08-27 08:26 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +    fetch("http://10.58.1.69:8000/user/signin", {
적용시켰습니다. 이렇게 또 새로운 공부 하게 해주셔서 감사합니다~~

2020-08-27 08:29 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +    fetch("http://10.58.1.69:8000/user/signin", {
200oK
API 주소는 웬만하면 동일하고 하나의 프로젝트 폴더의 여러 파일에서 fetch 를 실행시키기 때문에 API 주소가 바뀌게 되면 전부 바꾸는 것은 귀찮은 작업이기 때문에 하나만 바꾸면 되게 따로 관리한다.

2020-08-27 08:38 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +      visible: this.state.visible === "표시" ? "숨김" : "표시",
행복합니다 ㅎㅎ

2020-08-27 08:47 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +        isChecked: this.state.isChecked === false ? true : false,
적용시켰습니다!!!!!!!!!!!!

2020-08-27 13:20 UTC, jamessoun93 requested changes

2020-08-27 13:20 UTC, jamessoun93 commented on src/Components/CommonNav/CommonNav.js
> +    }
👍👍👍

2020-08-27 13:20 UTC, jamessoun93 commented on src/Components/CommonNav/CommonNav.js
> +export default withRouter(CommonNav);
`withRouter` 로 감싸신 이유가 있나요? 보니까 router 쪽에서 넘겨주는 API 들을 활용하는 곳이 없는 것 같아서요!

2020-08-27 13:20 UTC, jamessoun93 commented on src/Pages/LogIn/LoginScreen.js
> +  };
👍

2020-08-27 13:20 UTC, jamessoun93 commented on src/Pages/LogIn/LoginScreen.js
> +        }),
깨알 팁이지만, 아래와 같이 변경할 수 있습니다 ㅎㅎ
```suggestion
        body: JSON.stringify({
          email,
          password,
        }),
```

2020-08-27 13:20 UTC, jamessoun93 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +    }
signup POST 가 성공적일 시 바로 signin POST 를 보내는데, 별도의 로그인 절차는 필요없는건가요?

2020-08-27 13:20 UTC, jamessoun93 commented on src/Pages/Main/Models/Models.js
> +    }
이런 부분이 보이면 항상! 고민을 해봐야합니다!
반복적으로 보이는 부분이 굉장히 많죠? 여기 같은 경우는 model3 인지 modelS 인지 modelX 인지 여부만으로 state의 key 값들이 전부 바뀌는데요.
이럴 때 객체를 사용하면 해당 메소드가 훨씬 간결해질 수 있습니다.
외부 파일에서 객체를 선언해 각 모델별 정보를 객체로 담아둔 뒤 들어오는 className 을 이용해 해당 값들을 통째로 가져와서 setState 할 수 있겠죠! 

리뷰 토대로 적용해보시고 자랑타임 해주세요 휘찬님 😉

2020-08-27 16:58 UTC, chan-97 commented on src/Components/CommonNav/CommonNav.js
> +    }
칭찬 행복합니다 😁

2020-08-27 17:01 UTC, chan-97 commented on src/Components/CommonNav/CommonNav.js
> +export default withRouter(CommonNav);
공통 nav 바에서 링크 이동할 때 history.push 랑 Link 중 어떤것을 사용할지 고민하다 칠칠맞게 남긴 흔적입니다 ㅎ
수정했습니다!

2020-08-27 17:09 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +        }),
우와.... 꿀팁bbb
그런데 destructuring 을 하지 않았다면
```
  body: JSON.stringify({
          email: this.state.email,
          password: this.state.password,
        }),
```
였을 것입니다. 
혹시 이렇게 key 와 value 가 동일하지 않아도 가능한 것인지,

아니면 destructuring 을해서 key와 value 가 동일해 져서 가능한 것인지 궁금함이 생기네요!

2020-08-27 17:19 UTC, chan-97 commented on src/Pages/LogIn/SignUp/SignUpScreen.js
> +    }
음... 제가 실제로 테슬라 사이트에서 회원가입을 해본 결과
성, 이름, 이메일, 패스워드를 조건에 맞춰 작성하고 계정생성 버튼을 누르면 곧바로 로그인이 된 상태로 마이페이지로 이동하더라구요
별도의 로그인 절차는 없는 것임을 확인했습니다!
혹시 다른 의견 있으신거면 조언 부탁드려요!!

2020-08-27 17:40 UTC, saengmotmi commented on src/Pages/LogIn/LoginScreen.js
> +        }),
@chan-97 객체의 key와 value의 변수명이 같으면 객체 단축 속성명을 활용해 위 코드처럼 간단히 적어줄 수 있습니다!

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Object_initializer

2020-08-27 18:10 UTC, chan-97 commented on src/Pages/Main/Models/Models.js
> +    }
우ㅘ....
적용했습니다...
이부분은 스스로 구현해 내면서 굉장히 뿌듯했지만, 한편으로는 지적해주신 부분처럼 반복되는 부분이 거슬렸었습니다.
승현님 피드백 덕분에 이렇게 가독성이 좋은 로직을 작성할 수 있어서 너무 행복합니다🤗🤗🤗🤗

2020-08-27 18:19 UTC, chan-97 commented on src/Pages/LogIn/LoginScreen.js
> +        }),
최종적으로 사용되는 객체의 key 와 value의 변수명이 같이면 단축 속성명 사용이 가능하다!!
감사합니다😁

2020-08-28 03:01 UTC, merged

2020-08-29 15:44 UTC, chan-97 commented on src/Pages/Main/Models/Models.js
> +    }
승현님 리뷰 확인한 직후 이부분을 바로 적용시켰는데 전달을 못드린 것 같네요! ㅎㅎ

```
const modelsData = {
  model3: {
    title: "Model 3",
    backgroundPosition: "50%",
    storeBtn: false,
    btnColorS: "",
    btnBorderColorS: "",
    btnColor3: "white",
    btnBorderColor3: "white",
    btnColorX: "",
    btnBorderColorX: "",
  },
  modelS: {
    title: "Model S",
    backgroundPosition: "0%",
    storeBtn: true,
    btnColorS: "white",
    btnBorderColorS: "white",
    btnColor3: "",
    btnBorderColor3: "",
    btnColorX: "",
    btnBorderColorX: "",
  },
  modelX: {
    title: "Model X",
    backgroundPosition: "100%",
    storeBtn: true,
    btnColorS: "",
    btnBorderColorS: "",
    btnColor3: "",
    btnBorderColor3: "",
    btnColorX: "white",
    btnBorderColorX: "white",
  },
};

export default modelsData;

```

저같은 경우 이렇게 modelsData 라는 js파일을 따로 만든 후, 원래 이 로직을 사용하고 있었던
Models.js 에서 import 받아 원래 부분을

```
  viewChangeEffect = (e) => {
    if (e.target.className === "model3") {
      this.setState(modelsData.model3);
    } else if (e.target.className === "modelS") {
      this.setState(modelsData.modelS);
    } else {
      this.setState(modelsData.modelX);
    }
  };
```

이렇게 간단하게 만들수 있었습니다. 너무 감사해요!!!